"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";

/**
 * The application frame.
 *
 * Navigation is a fixed left rail rather than a top bar, because every screen here is
 * dense and vertical space is the scarce resource — a blotter wants every pixel of height
 * it can get, and horizontal space is comparatively free on the wide monitors this is
 * used on.
 */

const NAV = [
  { href: "/", label: "Dashboard", hint: "Performance at a glance" },
  { href: "/trades", label: "Trades", hint: "Every reconstructed round turn" },
  { href: "/patterns", label: "Patterns", hint: "Behavioural leaks and edges" },
  { href: "/reports", label: "Reports", hint: "Daily through annual" },
  { href: "/jobs", label: "Jobs", hint: "Background work" },
] as const;

export function Shell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  return (
    <div className="flex min-h-screen">
      <nav className="flex w-56 shrink-0 flex-col border-r border-slate-800 bg-[#0b1017]">
        <div className="border-b border-slate-800 px-4 py-4">
          <span className="font-mono text-sm font-semibold tracking-tight text-slate-100">
            LEDGERLINE
          </span>
          <p className="mt-0.5 text-[10px] uppercase tracking-widest text-slate-600">
            Trading journal
          </p>
        </div>

        <ul className="flex flex-1 flex-col gap-0.5 p-2">
          {NAV.map((item) => {
            const active =
              item.href === "/"
                ? pathname === "/"
                : pathname.startsWith(item.href);
            return (
              <li key={item.href}>
                <Link
                  href={item.href}
                  title={item.hint}
                  aria-current={active ? "page" : undefined}
                  className={`block rounded px-3 py-2 text-sm transition-colors ${
                    active
                      ? "bg-slate-800 text-slate-100"
                      : "text-slate-400 hover:bg-slate-800/50 hover:text-slate-200"
                  }`}
                >
                  {item.label}
                </Link>
              </li>
            );
          })}
        </ul>

        {/* The product's central claim, kept in front of whoever is using it. */}
        <p className="border-t border-slate-800 p-3 text-[10px] leading-relaxed text-slate-600">
          Every statistic here is computed in Python. Nothing on this screen is
          generated by a language model.
        </p>
      </nav>

      <main className="flex-1 overflow-x-auto">{children}</main>
    </div>
  );
}

export function PageHeader({
  title,
  subtitle,
  actions,
}: {
  title: string;
  subtitle?: string;
  actions?: React.ReactNode;
}) {
  return (
    <header className="flex items-start justify-between gap-4 border-b border-slate-800 px-6 py-4">
      <div>
        <h1 className="text-lg font-medium text-slate-100">{title}</h1>
        {subtitle ? (
          <p className="mt-0.5 text-xs text-slate-500">{subtitle}</p>
        ) : null}
      </div>
      {actions ? <div className="flex gap-2">{actions}</div> : null}
    </header>
  );
}
